-- ColdReach MVP — Supabase PostgreSQL Schema
-- Created: 2026-06-08
-- This schema should be run in Supabase SQL Editor

-- ============================================
-- EXTENSIONS
-- ============================================

-- Enable vector support for RAG/similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- USERS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  -- Indexes for common queries
  CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_created_at ON users(created_at);

-- ============================================
-- CAMPAIGNS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Campaign metadata
  cv_content TEXT NOT NULL,                    -- Raw CV text
  target_location VARCHAR(50) NOT NULL,        -- SF, NYC, Seattle
  target_role VARCHAR(100) NOT NULL,           -- SWE, Backend, Frontend, etc.

  -- Status tracking
  status VARCHAR(50) DEFAULT 'draft',          -- draft, leads_found, emails_generated, sent, completed

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  -- Metadata for tracking
  leads_count INTEGER DEFAULT 0,
  emails_sent INTEGER DEFAULT 0
);

CREATE INDEX idx_campaigns_user_id ON campaigns(user_id);
CREATE INDEX idx_campaigns_status ON campaigns(status);
CREATE INDEX idx_campaigns_created_at ON campaigns(created_at);

-- ============================================
-- LEADS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,

  -- Apollo.io data
  apollo_id VARCHAR(255),                      -- External ID from Apollo

  -- Person info
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(255) NOT NULL,

  -- Company info
  company_name VARCHAR(255),
  job_title VARCHAR(255),
  linkedin_url VARCHAR(500),

  -- Technical profile
  tech_stack TEXT,                             -- JSON array of technologies
  recent_posts TEXT,                           -- JSON array of recent LinkedIn posts

  -- Verification
  email_verified BOOLEAN DEFAULT FALSE,

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_leads_campaign_id ON leads(campaign_id);
CREATE INDEX idx_leads_email ON leads(email);
CREATE INDEX idx_leads_apollo_id ON leads(apollo_id);
CREATE INDEX idx_leads_company ON leads(company_name);

-- ============================================
-- GENERATED EMAILS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS generated_emails (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,

  -- Email content (generated by Claude)
  subject VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,

  -- Metadata
  personalization_notes TEXT,                  -- Why this email is personalized for this lead
  model_used VARCHAR(100),                     -- Which Claude model was used

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_generated_emails_lead_id ON generated_emails(lead_id);

-- ============================================
-- EMAIL SENDS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS email_sends (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  generated_email_id UUID NOT NULL REFERENCES generated_emails(id) ON DELETE CASCADE,

  -- Resend tracking
  resend_message_id VARCHAR(255),              -- Message ID from Resend API

  -- Status & timestamps
  status VARCHAR(50) DEFAULT 'pending',        -- pending, delivered, bounced, opened, clicked
  sent_at TIMESTAMP DEFAULT NOW(),
  delivered_at TIMESTAMP,
  opened_at TIMESTAMP,
  clicked_at TIMESTAMP,

  -- Metadata
  bounce_reason TEXT,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_email_sends_generated_email_id ON email_sends(generated_email_id);
CREATE INDEX idx_email_sends_status ON email_sends(status);
CREATE INDEX idx_email_sends_sent_at ON email_sends(sent_at);
CREATE INDEX idx_email_sends_resend_message_id ON email_sends(resend_message_id);

-- ============================================
-- EMBEDDINGS TABLE (for RAG/Vector Search)
-- ============================================

CREATE TABLE IF NOT EXISTS embeddings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,

  -- Type of embedding
  embedding_type VARCHAR(50) NOT NULL,        -- 'tech_stack', 'linkedin_post', 'job_title'

  -- Original content (for reference)
  content TEXT NOT NULL,

  -- The vector embedding (1536-dim from OpenAI)
  embedding vector(1536) NOT NULL,

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_embeddings_lead_id ON embeddings(lead_id);
CREATE INDEX idx_embeddings_type ON embeddings(embedding_type);

-- Vector similarity search index (using ivfflat for speed)
CREATE INDEX ON embeddings USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- ============================================
-- AUDIT TRAIL (Optional - for future use)
-- ============================================

CREATE TABLE IF NOT EXISTS audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,               -- 'campaign_created', 'email_sent', etc.
  resource_type VARCHAR(100),                 -- 'campaign', 'lead', 'email'
  resource_id UUID,
  details JSONB,                              -- Additional context as JSON

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX idx_audit_log_created_at ON audit_log(created_at);

-- ============================================
-- CONSTRAINTS & RULES
-- ============================================

-- Campaigns belong to users (enforced by FK)
-- Leads belong to campaigns (enforced by FK)
-- Emails belong to leads (enforced by FK)
-- Email sends track individual emails (enforced by FK)

-- ============================================
-- ROW LEVEL SECURITY (Optional - for future)
-- ============================================

-- Uncomment and configure RLS if you want to use Supabase Auth policies
-- ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE generated_emails ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE email_sends ENABLE ROW LEVEL SECURITY;

-- Example RLS policy (users can only see their own campaigns):
-- CREATE POLICY "Users can view their own campaigns"
--   ON campaigns FOR SELECT
--   USING (auth.uid() = user_id);

-- ============================================
-- VIEWS (Optional - for convenience)
-- ============================================

-- View: Campaign summary with counts
CREATE OR REPLACE VIEW campaign_summary AS
SELECT
  c.id,
  c.user_id,
  c.target_location,
  c.target_role,
  c.status,
  COUNT(DISTINCT l.id) as leads_count,
  COUNT(DISTINCT ge.id) as emails_count,
  COUNT(DISTINCT es.id) as sends_count,
  SUM(CASE WHEN es.status = 'delivered' THEN 1 ELSE 0 END) as delivered_count,
  SUM(CASE WHEN es.status = 'opened' THEN 1 ELSE 0 END) as opened_count,
  c.created_at,
  c.updated_at
FROM campaigns c
LEFT JOIN leads l ON c.id = l.campaign_id
LEFT JOIN generated_emails ge ON l.id = ge.lead_id
LEFT JOIN email_sends es ON ge.id = es.generated_email_id
GROUP BY c.id, c.user_id, c.target_location, c.target_role, c.status, c.created_at, c.updated_at;

-- ============================================
-- INITIAL MIGRATION NOTES
-- ============================================

-- After running this schema:
-- 1. Go to Authentication settings and enable Email/Password provider
-- 2. Test by creating a user in Supabase Auth
-- 3. Test by manually inserting data into the users table
-- 4. Verify all indexes are created
-- 5. Test vector search with a sample embedding

-- To verify setup:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
-- SELECT * FROM pg_indexes WHERE tablename IN ('users', 'campaigns', 'leads', 'generated_emails', 'email_sends', 'embeddings');
